On 340 endpoint for my account
Dvi55/game-shop pull request #33
Opened 2024-07-16 19:08 UTC by Liyto1

I made the only one PUT endpoint for updte information

2024-07-18 13:12 UTC, Dvi55 requested changes

2024-07-18 13:12 UTC, Dvi55 commented on src/main/java/com/gameshop/ecommerce/user/controller/MyAccountController.java
> +@RequestMapping("/my_account")
In our case it is better to name the path “users” or something like that. Underscore cannot be used in rest uri according to rules

2024-07-18 13:12 UTC, Dvi55 commented on src/main/java/com/gameshop/ecommerce/user/controller/MyAccountController.java
> +    @GetMapping("/{userId}")
We can use @AuthenticationPrincipal in this case. This is a better and easier way to implement user identification

2024-07-18 13:12 UTC, Dvi55 commented on src/main/java/com/gameshop/ecommerce/user/service/MyAccountService.java
> +    @Autowired
If we use lombok annotation to DI by constructor in controller, why cant we use it(annotation) in other classes?
So we dont need constructor, but need @RequiredArgsConstructor

2024-07-18 13:12 UTC, Dvi55 commented on src/main/java/com/gameshop/ecommerce/user/service/MyAccountService.java
> +    public LocalUserDto updateInfo(UUID userId, LocalUserDto userDto){
you need to rewrite all methods under @AuthenticationPrincipal

2024-07-18 13:12 UTC, Dvi55 commented on src/main/java/com/gameshop/ecommerce/user/service/MyAccountService.java
> +        LocalUser user = localUserDAO.findById(userId)
We have UserNotFoundExc

2024-07-18 13:12 UTC, Dvi55 commented on src/main/java/com/gameshop/ecommerce/user/service/MyAccountService.java
> +    public LocalUserDto updateInfo(UUID userId, LocalUserDto userDto){
I think it would be better to rewrite this method and make it more concise and readable

2024-07-18 13:12 UTC, Dvi55 commented on src/main/java/com/gameshop/ecommerce/user/service/MyAccountService.java
> +            LocalUser updatedUser = localUserDAO.save(user);
If user want change password, but send incorrect old pw, we need inform about it

2024-07-18 13:12 UTC, Dvi55 commented on src/main/java/com/gameshop/ecommerce/user/service/MyAccountService.java
> +    public LocalUserDto updateInfo(UUID userId, LocalUserDto userDto){
And you need to read about PUT and PATCH

2024-07-18 14:52 UTC, Liyto1 commented on src/main/java/com/gameshop/ecommerce/user/controller/MyAccountController.java
> +@RequestMapping("/my_account")
Done.
Named it "account"

2024-07-18 14:52 UTC, Liyto1 commented on src/main/java/com/gameshop/ecommerce/user/service/MyAccountService.java
> +    @Autowired
Done

2024-07-18 14:54 UTC, Liyto1 commented on src/main/java/com/gameshop/ecommerce/user/service/MyAccountService.java
> +        LocalUser user = localUserDAO.findById(userId)
Done

2024-07-22 15:08 UTC, Dvi55 approved these changes

2024-07-22 15:08 UTC, merged